# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV['FASTLANE_HIDE_CHANGELOG'] = 'true'
ENV['FASTLANE_SKIP_UPDATE_CHECK'] = 'true'

desc 'Run all the tests suites of the project'
lane :test do
  clear_derived_data
  update_pods
  test_tvos
  lint
end

desc 'Check style and conventions'
lane :lint do
  rubocop
  swiftlint(executable: 'Pods/SwiftLint/swiftlint', strict: true)
end

desc 'Update CocoaPods'
private_lane :update_pods do
  cocoapods(repo_update: true)
end

desc 'Run all the tests suites of the project for tvOS'
private_lane :test_tvos do
  scan(scheme: 'TvOSGoogleIMATest', device: 'Apple TV 4K (13.3)')
end
